[package]
name = "plistserver"
version = "0.2.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.5"
serde_json = "1.0"
env_logger = "0.9"
plist = { version = "1.7", features = ["serde"] }
log = "0.4"
